# Solarized Osaka
# Converted from Solarized Osaka terminal palette

background=#00121a
foreground=#bbd5d7

# Normal ANSI colors
color0=#1b232c
color1=#d1453d
color2=#75931e
color3=#c19522
color4=#2f86d7
color5=#c43c7c
color6=#2fa59f
color7=#d3d6d9

# Bright ANSI colors
color8=#576375
color9=#f3736b
color10=#b7d92e
color11=#ebcb58
color12=#6bbaf6
color13=#f065a9
color14=#50bbad
color15=#f9f8f6
